## Numpy
## Каткова Полина

##### Задание 1: Взять из документации по numpy 12 любых функций / методов / операторов и продемонстрировать из работу в блокноте. 


In [38]:
import numpy as np

In [39]:
np.eye(5) # 1 Создает квадратную матирицу заданного размера с еденицами на главной диагонали и нулями в остальных ячейках

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a = np.arange(0,5,0.5) # 2 Создает одномерный массив с равномерно распределенными значениями внутри указанного интервала
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [41]:
b = np.geomspace(1, 100, num = 10) # 3 Создает одномерный массив значений, которые представляют собой геометрическую прогрессию
print(b)

[  1.           1.66810054   2.7825594    4.64158883   7.74263683
  12.91549665  21.5443469   35.93813664  59.94842503 100.        ]


In [42]:
np.concatenate([a, b])# 4 Соеденяет последовательность массивов в один

array([  0.        ,   0.5       ,   1.        ,   1.5       ,
         2.        ,   2.5       ,   3.        ,   3.5       ,
         4.        ,   4.5       ,   1.        ,   1.66810054,
         2.7825594 ,   4.64158883,   7.74263683,  12.91549665,
        21.5443469 ,  35.93813664,  59.94842503, 100.        ])

In [43]:
c = np.random.randint(1, 100, size = (4, 5)) # 5 Генерация матрици заполненой псевдорандомными числами
c

array([[67, 40, 72, 33, 54],
       [54, 67, 67, 22, 10],
       [47, 52, 16,  3, 50],
       [62, 74, 76, 61, 12]])

In [44]:
np.random.shuffle(c) # 6 Перемешивает значения внутри массива
c

array([[54, 67, 67, 22, 10],
       [62, 74, 76, 61, 12],
       [67, 40, 72, 33, 54],
       [47, 52, 16,  3, 50]])

In [45]:
n = np.random.randint(1, 100, size = 20)
np.std(n) # 7 Среднеквадратическое отклонение

32.32069770286527

In [46]:
np.c_[1,2,3,4]  # 8 Записывает каждый n-й элемент в n-й столбец матрицы

array([[1, 2, 3, 4]], dtype=int32)

In [47]:
k = np.random.randint(0, 100, 15)
k

array([77,  5, 70, 53, 40, 14, 60, 44, 48, 34, 76, 94, 11,  2, 80])

In [48]:
np.sort(k) # 9 Соритрует массив

array([ 2,  5, 11, 14, 34, 40, 44, 48, 53, 60, 70, 76, 77, 80, 94])

In [49]:
np.argmax(a) #10 Находит индекс максимального значения в массиве

9

In [50]:
cond_1 = a%3 == 0 # Условие кратности на 3

In [51]:
np.extract(cond_1, k) #11 Находит элементы в массиве, удовлетворяющие заданному условию

array([77, 60])

In [52]:
np.linalg.qr(c) #12 QR-разложение матрицы

(array([[-0.46548265, -0.41393932, -0.28895939, -0.7269681 ],
        [-0.53444304, -0.38563869, -0.31026699,  0.68511884],
        [-0.57754329,  0.80752604, -0.11056295, -0.04605732],
        [-0.40514231, -0.16684942,  0.89889527, -0.00287768]]),
 array([[-116.00862037, -114.90525409, -119.87040235,  -63.11599928,
          -62.51259585],
        [   0.        ,  -32.64632572,   -1.57019079,   -6.48281424,
           26.496878  ],
        [   0.        ,    0.        ,  -36.51877792,  -26.23528416,
           32.36156656],
        [   0.        ,    0.        ,    0.        ,   24.27042684,
           -1.67923383]]))

##### Задание 2: Сгенерировать OLAP-куб, где фиксируем продажи товаров в розничной сети по магазинам. Оси: 0: ID группы товаров, 1: ID магазина, 2: день месяца, в котором осуществляются продажи (предположим у нас в OLAP-кубе собраны продажи за месяц). Содержимое ячейки: продажи в тыс. рублей данной категории товаров в данном магазине в данный день.

In [53]:
tovar_1 = (10 - (5))*np.random.random_sample((3, 29))+ 5 # Продажы первого товара в 3х магазинах за февраль 2020
#(составляют от 5 до 10 тысяч рублей в день)
tovar_1

array([[7.65719032, 9.57971128, 7.65490543, 8.39704463, 5.36817548,
        6.7871467 , 6.40557102, 5.03101785, 9.32513327, 5.74793268,
        6.30183998, 5.40564529, 5.29340678, 6.66534044, 5.33182141,
        8.01560659, 9.59960744, 6.63190074, 6.54718308, 9.38531672,
        7.68810129, 6.0037177 , 6.21173118, 5.26628933, 8.4096565 ,
        6.5291638 , 6.82780952, 9.61325495, 9.23310436],
       [8.59634899, 6.99308044, 7.09981609, 7.65943581, 6.46483299,
        5.50441715, 5.8222224 , 5.47415651, 8.77035869, 7.69669051,
        6.85230594, 9.73431593, 7.50142655, 5.33138028, 7.79958978,
        7.17854281, 5.42141692, 8.89954463, 9.95391071, 7.5652249 ,
        8.56810521, 9.6040191 , 9.07035765, 5.73821191, 8.87400432,
        8.84683661, 7.36461139, 9.74078301, 9.5226085 ],
       [7.29222015, 5.57879138, 7.85140838, 9.37126212, 5.24621087,
        8.70412412, 6.07653691, 8.01033229, 7.52258044, 6.59068056,
        6.48331933, 8.43024285, 5.82668741, 8.17615337, 8.05638969,
  

In [54]:
tovar_2 = (15 - (10))*np.random.random_sample((3, 29))+ 10 # Продажы второго товара в 3х магазинах за февраль 2020
#(составляют от 10 до 15 тысяч рублей в день)
tovar_2

array([[11.32475269, 11.86302656, 10.92870197, 10.51865592, 12.4025441 ,
        13.52225942, 11.09707064, 13.6356186 , 12.22387067, 11.53920231,
        10.00723732, 10.35178145, 11.85466631, 13.6358226 , 12.5963055 ,
        13.05671595, 11.37852438, 12.98613168, 13.29062829, 14.32073968,
        12.09484384, 11.56864228, 11.46047262, 10.92801661, 13.72186881,
        13.15408879, 13.59769411, 10.27351085, 13.19100822],
       [14.23257003, 13.93067005, 14.5054579 , 11.15257062, 10.03111024,
        13.7329144 , 11.30421286, 13.64760519, 12.16176216, 11.24688141,
        10.31498208, 12.52439006, 10.26728796, 10.71834997, 12.08858603,
        12.16086267, 13.70441584, 10.43947117, 13.59556871, 13.76074163,
        10.89661586, 10.56824288, 11.34197197, 11.86253367, 14.7492955 ,
        14.1589903 , 11.85335999, 12.28405581, 11.06462786],
       [12.92755478, 11.33614913, 12.00110973, 13.3368023 , 10.38494648,
        12.46560404, 12.38040503, 14.21888027, 10.02541755, 11.29472529,
  

In [55]:
tovar_3 = (25 - (20))*np.random.random_sample((3, 29))+ 20 # Продажы 3-го товара в 3х магазинах за февраль 2020
#(составляют от 20 до 25 тысяч рублей в день)
tovar_3

array([[24.97036665, 21.90047754, 20.9988025 , 22.73782865, 21.06264673,
        21.60482212, 24.18395005, 24.89465773, 24.07497716, 23.44361314,
        20.44428044, 24.43133667, 24.81337222, 22.74324127, 21.05161154,
        20.14863129, 24.59459981, 23.82390787, 20.19987923, 21.21646218,
        23.7489829 , 23.25839664, 20.32641365, 21.32931742, 21.46299938,
        23.25797087, 21.84200672, 23.11633658, 21.14878912],
       [21.67115315, 21.32902509, 20.39317738, 21.11306172, 22.34231452,
        23.01602808, 20.26369407, 21.24789715, 22.90744038, 24.72432383,
        23.59490508, 23.50893031, 22.21859187, 22.69664499, 23.67296507,
        21.73834392, 22.81070747, 21.71622887, 21.77065607, 24.46415766,
        24.3431622 , 23.48694531, 23.53751227, 22.02606028, 22.8838101 ,
        24.30781599, 24.88225619, 22.19575422, 23.3951969 ],
       [24.63928058, 21.80160808, 20.43819968, 22.80405611, 23.50892142,
        23.71675803, 23.25576523, 21.09569046, 24.22324872, 23.7125295 ,
  

In [56]:
olap = np.vstack((tovar_1, tovar_2, tovar_3)) #объеденяем данные по товарам в один двумерный массив
olap.shape

(9, 29)

In [57]:
olap = np.reshape(olap, (3, 3, 29)) #объеденяем данные по товарам в OLAP-куб
olap.shape

(3, 3, 29)

In [58]:
for tovar in 0,1,2:
        for shop in 0,1,2:
            (olap[tovar][shop][21]) *=1.4 
            (olap[tovar][shop][9]) *=1.4 
            (olap[tovar][shop][24]) *=1.4 
#Продажи выросли 10, 22 и 25 февраля на 40% перед праздником и в день получения зп

In [59]:
olap

array([[[ 7.65719032,  9.57971128,  7.65490543,  8.39704463,
          5.36817548,  6.7871467 ,  6.40557102,  5.03101785,
          9.32513327,  8.04710575,  6.30183998,  5.40564529,
          5.29340678,  6.66534044,  5.33182141,  8.01560659,
          9.59960744,  6.63190074,  6.54718308,  9.38531672,
          7.68810129,  8.40520479,  6.21173118,  5.26628933,
         11.7735191 ,  6.5291638 ,  6.82780952,  9.61325495,
          9.23310436],
        [ 8.59634899,  6.99308044,  7.09981609,  7.65943581,
          6.46483299,  5.50441715,  5.8222224 ,  5.47415651,
          8.77035869, 10.77536671,  6.85230594,  9.73431593,
          7.50142655,  5.33138028,  7.79958978,  7.17854281,
          5.42141692,  8.89954463,  9.95391071,  7.5652249 ,
          8.56810521, 13.44562673,  9.07035765,  5.73821191,
         12.42360605,  8.84683661,  7.36461139,  9.74078301,
          9.5226085 ],
        [ 7.29222015,  5.57879138,  7.85140838,  9.37126212,
          5.24621087,  8.70412412,  6.0

In [60]:
np.mean(olap) #Cреднее значение продаж за 1 день во всех магазинах по всем товарам

14.669884142111965

In [61]:
np.mean(olap[0]) #Cреднее значение продаж 1го товара

7.689253362164516

In [62]:
np.mean(olap[2][0][1:10]) #Cреднее значение продаж 2го товара c 1 по 9 число

23.80880232060568

In [63]:
np.mean(olap[2][0][19:28]) #Cреднее значение продаж 2го товара c 20 по 29 число

24.16082719501966

In [64]:
np.min(olap[2]) #Минимальное значение продаж 3го товара

20.14863129393448

In [65]:
np.sum(olap[1][2]) #Сумарное значение продаж 2го товара в 3 магазине

371.170881755652

In [66]:
np.sum(olap[1][2][21])/np.sum(olap[1][2][1]) #Разница продаж 2-го товара в 3 магазмне между 22 и 2 февраля

1.305234589792677